In [2]:
import pandas as pd
import seaborn as sns

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset("anagrams")

In [11]:
import os
os.getcwd()
os.listdir()

['calculator.ipynb',
 'class 14 and 15.py',
 'for loop practice pml.py',
 'for loop practice.py',
 'hard function practice.py',
 'my_data.csv',
 'my_data.xlsx',
 'pml2507 classwork.py',
 'practice.py',
 'practice_dataset.ipynb',
 '__pycache__']

In [10]:
os.getcwd()

'c:\\Users\\ASUS\\OneDrive\\ドキュメント\\Custom Office Templates'

In [12]:
df.to_excel("my_data.xlsx")

In [13]:
df1 = pd.read_csv("my_data.csv")

In [14]:
df1

     Name  Age    City
0   Rahim   22   Dhaka
1   Karim   25  Khulna
2  Ayesha   21  Sylhet

In [ ]:
df2 = pd.read_excel("my_data.xlsx")

In [15]:
df2

NameError: name 'df2' is not defined

In [16]:
df.head()

   subidr    attnr  num1  num2  num3
0       1  divided     2   4.0     7
1       2  divided     3   4.0     5
2       3  divided     3   5.0     6
3       4  divided     5   7.0     5
4       5  divided     4   5.0     8

In [17]:
df.tail(3)

    subidr    attnr  num1  num2  num3
17      18  focused     7   8.0     6
18      19  focused     5   6.0     6
19      20  focused     6   6.0     5

In [18]:
df[10:15]

    subidr    attnr  num1  num2  num3
10      11  focused     6   5.0     6
11      12  focused     8   9.0     8
12      13  focused     6   5.0     9
13      14  focused     8   8.0     7
14      15  focused     8   8.0     7

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\NLP\\my_data.csv'